# 环境配置
server:
  # 服务器的HTTP端口，默认为80
  port: 80
  servlet:
    # 应用的访问路径
    context-path: /life
  tomcat:
    # 最大吞吐量
    max-swallow-size: -1
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30
  compression:
    # 开启压缩
    enabled: true
    # 指定要压缩的MIME type，多个以逗号分隔.
    mime-types: application/javascript,application/json,application/xml,text/html,text/xml,text/plain,text/css,image/*

# 日志配置
## 选项 TRACE, DEBUG, INFO, WARN, ERROR, FATAL, OFF
logging:
  level:
    org.springframework: WARN
    design.life: DEBUG
